// Auto-generated by TTmek AutoCRUD at Sun Feb 02 22:26:41 CST 2020

package com.ttmek.autocrud.mapper;

import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Service;
import java.util.List;
import com.ttmek.autocrud.model.Project;


@Service
public interface ProjectsMapper {
    @Insert("INSERT INTO projects(user_id, group_id, artifact_id, version, description, content) VALUES(#{userId}, #{groupId}, #{artifactId}, #{version}, #{description}, #{content})")
    @Options(useGeneratedKeys=true, keyProperty="projectId", keyColumn="project_id")
    void create(Project project);

    @Select("SELECT * FROM projects WHERE project_id = #{projectId}")
    @Results({
        @Result(property = "projectId", column = "project_id"),
        @Result(property = "userId", column = "user_id"),
        @Result(property = "groupId", column = "group_id"),
        @Result(property = "artifactId", column = "artifact_id"),
        @Result(property = "version", column = "version"),
        @Result(property = "description", column = "description"),
        @Result(property = "content", column = "content")
    })
    List<Project> retrieve(String projectId);

    @Select("SELECT * FROM projects")
    @Results({
            @Result(property = "projectId", column = "project_id"),
            @Result(property = "userId", column = "user_id"),
            @Result(property = "groupId", column = "group_id"),
            @Result(property = "artifactId", column = "artifact_id"),
            @Result(property = "version", column = "version"),
            @Result(property = "description", column = "description"),
            @Result(property = "content", column = "content")
    })
    List<Project> retrieveAll();

    @Update("UPDATE projects SET user_id = #{userId}, group_id = #{groupId}, artifact_id = #{artifactId}, version = #{version}, description = #{description}, content = #{content} WHERE project_id = #{projectId}")
    void update(Project project);

    @Delete("DELETE FROM projects WHERE project_id = #{projectId}")
    void delete(String projectId);
}

