package com.mekcone.excrud.codegen.constant;

import java.io.File;

public interface ApplicationParameter {
    String EXCRUD_HOME = System.getenv("EXCRUD_HOME") + File.separator;
    String DESCRIPTION = "Generated by MekCone ExCRUD";
}
