package com.mekcone.excrud.codegen.constant;

public interface ModuleConstant {
    // Common
    String DESCRIPTION = "Generated by MekCone ExCRUD";
    String MODULE_TYPE_DOCUMENT = "document";
    String MODULE_TYPE_DEPLOYMENT = "deployment";
    String MODULE_TYPE_DATASOURCE = "datasource";
    String MODULE_TYPE_HYBRID_MOBILE_APP = "hybrid-mobile-app";
    String MODULE_TYPE_SPRING_BOOT = "spring-boot";
    String MODULE_TYPE_VUE_ELEMENT_ADMIN = "vue-element-admin";
    String MODULE_TYPE_WEBSITE_PAGE = "website-page";


    // Datasource
    String DATASOURCE_REDIS_MODE_SINGLE = "single";
    String DATASOURCE_REDIS_MODE_MASTER_SLAVE = "master-slave";
    String DATASOURCE_REDIS_MODE_SENTINEL = "sentinel";
    String DATASOURCE_REDIS_MODE_CLUSTER = "cluster";


    // Deployment
    String DEPLOYMENT_DAEMON_CRONTAB = "crontab";
    String DEPLOYMENT_DAEMON_DOCKER = "docker";
    String DEPLOYMENT_DAEMON_SUPERVISOR = "supervisor";
    String DEPLOYMENT_DAEMON_SYSTEMD = "systemd";


    String DEPLOYMENT_EXTENSION_MARIADB = "mariadb";
    String DEPLOYMENT_EXTENSION_MONGODB = "mongodb";
    String DEPLOYMENT_EXTENSION_NGINX = "nginx";
    String DEPLOYMENT_EXTENSION_SUPERVISOR = "supervisor";

    String DEPLOYMENT_OPERATING_SYSTEM_UBUNTU = "ubuntu";
    String DEPLOYMENT_OPERATING_SYSTEM_CENTOS = "centos";


    // Document
    String DOCUMENT_KEYWORD_CREATE = "create";
    String DOCUMENT_KEYWORD_RETRIEVE = "retrieve";
    String DOCUMENT_KEYWORD_UPDATE = "update";
    String DOCUMENT_KEYWORD_DELETE = "delete";

    String DOCUMENT_EXPORT_FORMAT_MARKDOWN = "md";
    String DOCUMENT_EXPORT_FORMAT_PDF = "pdf";


    // Spring Boot
    String SPRING_BOOT_COMPONENT_CONFIG = "config";
    String SPRING_BOOT_COMPONENT_CONTROLLER = "controller";
    String SPRING_BOOT_COMPONENT_ENTITY = "entity";
    String SPRING_BOOT_COMPONENT_EXCEPTION = "exception";
    String SPRING_BOOT_COMPONENT_MAPPER = "mapper";  // Mybatis only
    String SPRING_BOOT_COMPONENT_MODEL = "model";
    String SPRING_BOOT_COMPONENT_REPOSITORY = "repository";  // Hibernate only
    String SPRING_BOOT_COMPONENT_SERVICE = "service";
    String SPRING_BOOT_COMPONENT_SERVICE_IMPL = "serviceImpl";
    String SPRING_BOOT_COMPONENT_UTIL = "util";

    String SPRING_BOOT_EXTENSION_CROSS_ORIGIN = "cross-origin";
    String SPRING_BOOT_EXTENSION_LOMBOK = "lombok";
    String SPRING_BOOT_EXTENSION_MEKCONE_CLOUD = "mekcone-cloud";
    String SPRING_BOOT_EXTENSION_SWAGGER2 = "swagger2";
}
