package com.mekcone.excrud.model.file.xml;


import com.mekcone.excrud.model.file.FileModel;
import com.mekcone.excrud.model.project.components.Dependency;
import com.mekcone.excrud.util.LogUtil;
import com.mekcone.excrud.util.StringUtil;
import org.jdom2.Comment;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.Namespace;
import org.jdom2.output.Format;
import org.jdom2.output.XMLOutputter;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

@Component
public class PomXmlFileModel extends FileModel {

    private String groupId;
    private String artifactId;
    private String version;
    private List<Dependency> dependencies = new ArrayList<>();


    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }


    public void setArtifactId(String artifactId) {
        this.artifactId = artifactId;
    }


    public void setVersion(String version) {
        this.version = version;
    }

    public void setDependencies(List<Dependency> dependencies) {
        this.dependencies = dependencies;
    }

    @Override
    public String toString() {
        // Root
        Element rootElement = new Element("project");
        Document document = new Document(rootElement);
        rootElement.addContent(new Comment(getDescription()));
        Namespace xmlns = Namespace.getNamespace("http://maven.apache.org/POM/4.0.0");
        rootElement.setNamespace(xmlns);
        Namespace xsi = Namespace.getNamespace("xsi", "http://www.w3.org/2001/XMLSchema-instance");
        rootElement.addNamespaceDeclaration(xsi);
        rootElement.setAttribute("schemaLocation", "http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd", xsi);
        rootElement.addContent(new Element("modelVersion", xmlns).setText("4.0.0"));

        // Parent
        Element parentElement = new Element("parent", xmlns);
        rootElement.addContent(parentElement);
        parentElement.addContent(new Element("groupId", xmlns).setText("org.springframework.boot"));
        parentElement.addContent(new Element("artifactId", xmlns).setText("spring-boot-starter-parent"));
        parentElement.addContent(new Element("version", xmlns).setText("2.2.1.RELEASE"));
        parentElement.addContent(new Element("relativePath", xmlns));

        rootElement.addContent(new Element("groupId", xmlns).setText(groupId));
        rootElement.addContent(new Element("artifactId", xmlns).setText(artifactId));
        rootElement.addContent(new Element("version", xmlns).setText(version));
        rootElement.addContent(new Element("name", xmlns).setText(artifactId));
        rootElement.addContent(new Element("description", xmlns).setText(
                StringUtil.capitalize(artifactId) +
                        " Project auto-generated by com.mekcone.autocrud.AutoCRUD"
        ));

        // Properties
        Element propertiesElement = new Element("properties", xmlns);
        rootElement.addContent(propertiesElement);
        propertiesElement.addContent(new Element("java.version", xmlns).setText("1.8"));

        // Dependencies
        Element dependenciesElement = new Element("dependencies", xmlns);
        rootElement.addContent(dependenciesElement);

        for (Dependency dependency: this.dependencies) {
            Element dependencyElement = new Element("dependency", xmlns);
            dependencyElement.addContent(new Element("groupId", xmlns).setText(dependency.getGroupId()));
            dependencyElement.addContent(new Element("artifactId", xmlns).setText(dependency.getArtifactId()));
            if (dependency.getVersion() != null) {
                dependencyElement.addContent(new Element("version", xmlns).setText(dependency.getVersion()));
            }
            if (dependency.getScope() != null) {
                dependencyElement.addContent(new Element("scope", xmlns).setText(dependency.getScope()));
            }
            dependenciesElement.addContent(dependencyElement);
        }

        /*projectModel.addModule(new Module("web"));
        projectModel.addModule(new Module("mybatis"));

        for (Module module: projectModel.getModules()) {
            String groupId, artifactId, version = null, scope = null;
            switch (module.getId()) {
                case "mybatis":
                    groupId = "org.mybatis.spring.boot";
                    artifactId = "mybatis-spring-boot-starter";
                    version = "2.1.1";
                    break;
                case "mysql":
                    groupId = "mysql";
                    artifactId = "mysql-connector-java";
                    scope = "runtime";
                    break;
                case "redis":
                    groupId = "org.springframework.boot";
                    artifactId = "spring-boot-starter-data-redis";
                    break;
                case "web":
                    groupId = "org.springframework.boot";
                    artifactId = "spring-boot-starter-web";
                    break;
                default:
                    LogUtil.warn("Unknown module \"" + module.getId() + "\".");
                    continue;
            }
            Element dependencyElement = new Element("dependency", xmlns);
            dependencyElement.addContent(new Element("groupId", xmlns).setText(groupId));
            dependencyElement.addContent(new Element("artifactId", xmlns).setText(artifactId));
            if (version != null) {
                dependencyElement.addContent(new Element("version", xmlns).setText(version));
            }
            if (scope != null) {
                dependencyElement.addContent(new Element("scope", xmlns).setText(scope));
            }
            dependenciesElement.addContent(dependencyElement);
        }*/

        // Spring Boot Starter Test
        Element testDependencyElement = new Element("dependency", xmlns);
        testDependencyElement.addContent(new Element("groupId", xmlns).setText("org.springframework.boot"));
        testDependencyElement.addContent(new Element("artifactId", xmlns).setText("spring-boot-starter-test"));
        testDependencyElement.addContent(new Element("scope", xmlns).setText("test"));
        Element exclusionsElement = new Element("exclusions", xmlns);
        testDependencyElement.addContent(exclusionsElement);
        Element exclusionElement = new Element("exclusion", xmlns);
        exclusionsElement.addContent(exclusionElement);
        exclusionElement.addContent(new Element("groupId", xmlns).setText("org.junit.vintage"));
        exclusionElement.addContent(new Element("artifactId", xmlns).setText("junit-vintage-engine"));
        dependenciesElement.addContent(testDependencyElement);

        // <build></build>
        Element buildElement = new Element("build", xmlns);
        rootElement.addContent(buildElement);
        Element pluginsElement = new Element("plugins", xmlns);
        buildElement.addContent(pluginsElement);
        Element pluginElement = new Element("plugin", xmlns);
        pluginsElement.addContent(pluginElement);
        pluginElement.addContent(new Element("groupId", xmlns).setText("org.springframework.boot"));
        pluginElement.addContent(new Element("artifactId", xmlns).setText("spring-boot-maven-plugin"));

        // Generate string
        Format format = Format.getPrettyFormat();
        format.setEncoding("UTF-8");
        XMLOutputter xmlOutputter = new XMLOutputter(format);
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();

        try {
            xmlOutputter.output(document, byteArrayOutputStream);
        } catch (IOException e) {
            LogUtil.warn(e.getMessage());
        }
        return byteArrayOutputStream.toString();
    }
}
