-- Generated by MekCone EXCRUD at Mon May 18 12:40:52 CST 2020

CREATE DATABASE mekcone_mall;

CREATE TABLE goods (
    goods_id int NOT NULL AUTO_INCREMENT,
    goods_name varchar(50),
    catalogue_id varchar(50),
    goods_price double,
    goods_description varchar(50),
    PRIMARY KEY(goods_id)
);

CREATE TABLE cart (
    item_id varchar(50) NOT NULL AUTO_INCREMENT,
    goods_id varchar(50),
    user_id varchar(20),
    amount int,
    PRIMARY KEY(item_id)
);

CREATE TABLE catalogue (
    catalogue_id varchar(50) NOT NULL AUTO_INCREMENT,
    catalogue_name varchar(50),
    PRIMARY KEY(catalogue_id)
);

