package com.vancone.excode.generator.enums;

/**
 * @author Tenton Lien
 * @since 2021/07/24
 */
public enum TemplateType {
    DIRECTORY,
    RAW_FILE,
    SPRING_BOOT_APPLICATION_ENTRY,
    SPRING_BOOT_CONFIG_CROSS_ORIGIN,
    SPRING_BOOT_CONFIG_SWAGGER2,
    SPRING_BOOT_CONTROLLER,
    SPRING_BOOT_ENTITY,
    SPRING_BOOT_JPA_REPOSITORY,
    SPRING_BOOT_MYBATIS_ANNOTATION_MAPPER,
    SPRING_BOOT_POM,
    SPRING_BOOT_PROPERTIES,
    SPRING_BOOT_SERVICE_JPA,
    SPRING_BOOT_SERVICE_MYBATIS,
    SPRING_BOOT_SERVICE_IMPL_MYBATIS,
    SPRING_BOOT_SERVICE_IMPL_JPA,
    SQL,
    STATIC_TEMPLATE,
    VITE_ADMIN_PACKAGE_JSON,
    VITE_ADMIN_README_MD,
    VITE_ADMIN_SRC_APP_VUE,
    VITE_ADMIN_VITE_CONFIG_TS;
}
