// Auto-generated by TTmek AutoCRUD at Sun Feb 02 22:26:41 CST 2020

package com.ttmek.autocrud.controller;

import java.util.List;

import com.ttmek.autocrud.service.ProjectsService;
import org.springframework.web.bind.annotation.*;
import org.springframework.beans.factory.annotation.Autowired;
import com.ttmek.autocrud.model.RestResponse;
import com.ttmek.autocrud.model.Project;
import com.ttmek.autocrud.mapper.ProjectsMapper;


@RestController
@RequestMapping("/project")
public class ProjectsController {

    @Autowired
    private ProjectsService projectsService;

    @PostMapping
    RestResponse create(@RequestBody Project project) {
        if (projectsService.create(project)) {
            return RestResponse.success();
        }
        return RestResponse.fail(1, "Create project failed");
    }

    @GetMapping
    RestResponse retrieveAll() {
        List<Project> projectList = projectsService.retrieveAll();
        if (projectList == null) {
            return RestResponse.fail(1, "Retrieve project failed");
        }
        return RestResponse.success(projectList);
    }

    @GetMapping("/{projectId}")
    RestResponse retrieve(@PathVariable String projectId) {
        List<Project> projectList = projectsService.retrieve(projectId);
        if (projectList == null) {
            return RestResponse.fail(1, "Retrieve project failed");
        }
        return RestResponse.success(projectList);
    }


    @PutMapping
    RestResponse update(@RequestBody Project project) {
        if (projectsService.update(project)) {
            return RestResponse.success();
        }
        return RestResponse.fail(1, "Update project failed");
    }

    @DeleteMapping("/{projectId}")
    RestResponse delete(@PathVariable String projectId) {
        if (projectsService.delete(projectId)) {
            return RestResponse.success();
        }
        return RestResponse.fail(1, "Delete project failed");
    }
}