package com.vancone.excode.core.enums;

/**
 * @author Tenton Lien
 * @date 7/24/2021
 */
public enum TemplateType {
    SPRING_BOOT_APPLICATION_ENTRY,
    SPRING_BOOT_CONFIG_CROSS_ORIGIN,
    SPRING_BOOT_CONFIG_SWAGGER2,
    SPRING_BOOT_CONTROLLER,
    SPRING_BOOT_ENTITY,
    SPRING_BOOT_MYBATIS_ANNOTATION_MAPPER,
    SPRING_BOOT_POM,
    SPRING_BOOT_PROPERTIES,
    SPRING_BOOT_SERVICE,
    SPRING_BOOT_SERVICE_IMPL,
    SQL,
    VITE_ADMIN_PACKAGE_JSON
}
