<template>
  <div class="projectContainer">
    <el-button type="primary" class="button" @click="newProject">New Project</el-button>
    <el-button type="primary" class="button" @click="open">Open Project from Local Machine</el-button>
    <h1>Projects</h1>
    <el-table :data="projects" style="width:1000px;margin-left:20px;" stripe>
      <el-table-column prop="groupId" label="Group ID" width="250"></el-table-column>
      <el-table-column prop="artifactId" label="Artifact ID" width="250"></el-table-column>
      <el-table-column prop="version" label="Version" width="150"></el-table-column>
      <el-table-column prop="operations" label="Operations" width="300">
        <template slot-scope="scope">
          <el-button @click="editItem(scope.$index)">Edit</el-button>
          <el-button @click="editItem(scope.$index)">Download</el-button>
          <el-popconfirm title="Are you sure to delete this dependency?" @onConfirm="deleteItem(scope.$index)"
            confirmButtonText="Confirm"
            cancelButtonText='Cancel'>
            <el-button type="danger" slot="reference">Delete</el-button>
          </el-popconfirm>
        </template>
      </el-table-column>
    </el-table>
    <el-drawer
      title="New Project"
      :visible.sync="drawer"
      direction="rtl"
      :before-close="close"
      append-to-body="false"
      >
        <el-input placeholder="groupId" v-model="currentDependency.groupId" class="drawerInput"/>
        <el-input placeholder="artifactId" v-model="currentDependency.artifactId" class="drawerInput"/>
        <el-input placeholder="version" v-model="currentDependency.version" class="drawerInput"/>
        <el-input placeholder="description" v-model="currentDependency.description" class="drawerInput"/>
        <el-button type="primary" class="drawerButton" @click="save">OK</el-button>
    </el-drawer>
    <input type="file" name="file" id="file" class="file" @change="readFile"/>
  </div>
</template>

<script>
export default {
  name: 'Project',
  data () {
    return {
      currentDependency: {
        groupId: '',
        artifactId: '',
        version: '',
        description: ''
      },
      projects: [
        {
          projectId: '',
          groupId: '',
          artifactId: '',
          version: ''
        }
      ],
      drawer: false,
    }
  },
  methods: {
    newProject() {
      this.drawer = true
    },
    open() {
      document.getElementById('file').click()
    },
    deleteItem(index) {
      this.$axios({
        method:'delete',
        url:'http://192.168.1.103:9093/project/' + this.projects[index].projectId,
      }).then((response) => {
        console.log(response)
        if (response.data.code == 0) {
          this.$message({
            message: 'Delete project complete.',
            type: 'success'
          });
          this.getProjectList();
        } else {
          this.$message.error('Delete project failed');
        }
      }).catch((error) => {
        console.log(error)
        this.$message.error('Delete project failed');
      })
    },
    save() {
      if (this.currentDependency.groupId == '') {
        this.$message.error('"groupId" cannot be null.');
        return false
      } else if (this.currentDependency.artifactId == '') {
        this.$message.error('"artifactId" cannot be null.');
        return false
      }

      if (this.currentDependency.version == '') {
        this.currentDependency.version = '0.0.1'
      }

      if (this.currentDependency.description == '') {
        this.currentDependency.description = 'Auto-generated by AutoCRUD'
      }

      this.drawer = false
      this.$axios({
        method:'post',
        url:'http://192.168.1.103:9093/project',
        headers: {
          "Content-Type": "application/json;"
        },
        data: JSON.stringify(this.currentDependency)
      }).then((response) => {
        console.log(response)
        if (response.data.code == 0) {
          this.$message({
            message: 'Create project complete.',
            type: 'success'
          });
          this.getProjectList()
        } else {
          this.$message.error('Create project failed');
        }
      }).catch((error) => {
        console.log(error)
        this.$message.error('Create project failed');
      })
    },

    readFile() {
      var f = document.getElementById('file').files[0]
      if (f == null) {
        alert('Invalid project file')
        return
      }
      var reader = new FileReader()
      reader.readAsText(f)
      var that = this
      reader.onload = function(e) {
        that.$emit('submitProject', JSON.parse(e.target.result))
        that.$router.push('/overview')
      }
    },

    getProjectList() {
      this.$axios({
        method:'get',
        url:'http://192.168.1.103:9093/project',
      }).then((response) => {
        console.log(response)
        this.projects = response.data.data
      }).catch((error) => {
        console.log(error)
      })
    }
  },
  
  mounted: function() {
    this.getProjectList()
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.projectContainer {
  /* position: fixed;
  left: 0;
  top: 0; */
  background: #f7f9fa;
  color: black;
  /* padding: 5px; */
  /* text-align: center; */
  height: 100%;
  width: 100%;
  text-align: left;
  /* z-index: 1000; */
}
.button {
  margin-left: 20px;
  margin-top: 20px;
  margin-bottom: 20px;
}
h1 {
  font-weight: bold;
  font-size:20px;
  /* margin: 0; */
  margin-left: 20px;
}
/* .buttonContainer {
  position: absolute;
  margin: auto;
  left: 0;
  right: 0;
  top: 100px;
  bottom: 0;
  width: 500px;
  height: 300px;
}
.buttonContainer button {
  width: 400px;
  height: 80px;
  border-radius: 5px;
  background: #2091f6;
  color: white;
  outline: none;
  border: none;
  margin-top: 10px;
  margin-bottom: 10px;
  cursor: pointer;
  font-size: 22px;
}
.buttonContainer button:hover {
  background: #0e416f;
} */
.file {
  opacity: 0;
}
.drawerInput {
  margin-left: 20px;
  margin-bottom: 15px;
  display: block;
  width: calc(100% - 40px);
}
.drawerButton {
  margin-left: 20px;
  width: calc(100% - 40px);
}
</style>
